site_name: CyberCloud Learnings
site_url: https://cybercloud.guru/
site_description: Tutorials for Cloud Technologies and Cybersecurity, CloudSecurity, DevSecOps with an easy to understand examples and projects
site_author: Sanjeev Jaiswal (Jassi)
copyright: '&copy; Copyright 2022 - Developed with Care by CyberCloud Gurus'
repo_url: https://github.com/jassics/CybercloudLearning
repo_name: jassics/CybercloudLearning
edit_uri: blob/main/docs/

theme:
  name: material
  nav_style: dark
  logo: "assets/images/logo.png"
  favicon: "assets/images/favicon.png"
  analytics:
    gtag: G-ABC123
  features:
    - navigation.top
    - navigation.tabs
    - navigation.indexes
    - navigation.tracking
    - search.suggest
    - search.highlight
  icon:
    repo: fontawesome/brands/github
  palette:
    # Light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: light blue
      accent: blue grey
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    # Dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: light blue
      accent: light blue
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode

plugins:
  - search
  - minify:
      minify_html: true
      minify_js: true
      minify_css: true
      htmlmin_opts:
          remove_comments: true

nav:
    - Home: index.md
    - Cloud Computing:
      - 'Cloud Computing Essentials': cloud-computing/cloud-basics.md
      - 'Learning AWS':
        - 'AWS Overview': cloud-computing/learning-aws/index.md
        - 'IAM': cloud-computing/learning-aws/iam.md
        - 'EC2': cloud-computing/learning-aws/ec2.md
        - 'S3': cloud-computing/learning-aws/s3.md
        - 'VPC': cloud-computing/learning-aws/vpc.md
        - 'Lambda': cloud-computing/learning-aws/lambda.md
      - 'Learning GCP':
        - 'GCP Overview': cloud-computing/learning-gcp/index.md
      - 'Learning Azure':
            - 'Azure Overview': cloud-computing/learning-azure/index.md
    - Cloud Security:
      - 'Cloud Security Essentials': cloud-security/cloud-security-essentials.md
      - 'OWASP Top 10 Cloud': cloud-security/owasp-top10-cloud.md
      - 'Learning AWS Security':
        - 'AWS Security Overview': cloud-security/learning-aws-security/aws-security-overview.md
        - 'IAM Security': cloud-security/learning-aws-security/iam-security.md
        - 'S3 Security': cloud-security/learning-aws-security/s3-security.md
        - 'Cloudtrail': cloud-security/learning-aws-security/cloudtrail.md
        - 'GuardDuty': cloud-security/learning-aws-security/guardduty.md
        - 'KMS': cloud-security/learning-aws-security/kms.md
      - 'Learning GCP Security':
        - 'GCP Security Overview': cloud-security/learning-gcp-security/gcp-security-overview.md
      - 'Learning Azure Security':
        - 'Azure Security Overview': cloud-security/learning-azure-security/azure-security-overview.md
    - Containers:
        - 'Container Overview': containers/container-overview.md
        - 'Docker': containers/docker.md
        - 'Docker Security': containers/docker-security.md
        - 'Kubernetes': containers/kubernetes.md
        - 'Kubernetes Security': containers/kubernetes-security.md
    - Cybersecurity:
      - 'Cybersecurity Overview': cybersecurity/cybersecurity-overview.md
      - 'Common Security Concepts': cybersecurity/common-security-concepts.md
      - 'Web Security':
        - 'Web Security Overview': cybersecurity/web-security/web-security-overview.md
        - 'OWASP Top 10 2021': cybersecurity/web-security/owasp-top10.md
        - 'Web Security Concepts': cybersecurity/web-security/web-security-concepts.md
      - 'Network Security': cybersecurity/network-security.md
      - 'API Security': cybersecurity/api-security.md
      - 'Application Security':
          - 'Secure Coding': cybersecurity/application-security/secure-coding.md
          - 'Secure Code Review': cybersecurity/application-security/secure-code-review.md
          - 'Cryptography': cybersecurity/application-security/cryptography.md
          - 'Threat Modeling': cybersecurity/application-security/threat-modeling.md
          - 'SAST': cybersecurity/application-security/sast.md
          - 'SCA': cybersecurity/application-security/sca.md
    - DevOps:
        - 'Understanding DevOps': devops/devops-introduction.md
        - 'Ansible': devops/ansible.md
        - 'Terraform': devops/terraform.md
        - 'CloudFormation': devops/cloudformation.md
        - 'Pulumi': devops/pulumi.md
    - DevSecOps:
        - 'DevSecOps Fundamentals': devsecops/devsecops-fundamentals.md
        - 'DevSecOps Maturity Model': devsecops/devsecops-maturity.md
        - 'SDL in CI/CD Pipeline': devsecops/sdl-cicd.md
        - 'SCA in CI/CD Pipeline': devsecops/sca-cicd.md
        - 'DAST in CI/CD Pipeline': devsecops/dast-cicd.md
        - 'Compliance as a Code': devsecops/compliance-as-code.md
        - 'Automated Vulnerability Management': devsecops/vulnerability-management.md
    - GRC:
      - 'GRC Overview': grc/grc-overview.md
      - 'ISO/IEC 27001:2022': grc/iso27k1.md
      - 'Data Privacy': grc/data-privacy.md
      - 'GDPR': grc/gdpr.md
      - 'NIST RMF': grc/nist-rmf.md
      - 'NIST CSF': grc/nist-csf.md
    - Python Track:
        - 'Python Track Introduction': python-track/python-track-overview.md
        - 'Learning Python': python-track/learning-python.md
        - 'Python for AWS': python-track/python-for-aws.md
        - 'Python for Automation': python-track/python-for-automation.md
        - 'Python for DevOps': python-track/python-for-devops.md
        - 'Python for Cybersecurity': python-track/python-for-cybersecurity.md
    - Study Plan:
        - 'AWS Security Study Plan': study-plan/aws-security-study-plan.md
        - 'GCP Security Study Plan': study-plan/gcp-security-study-plan.md
        - 'DevSecOps Study Plan': study-plan/devsecops-study-plan.md
        - 'Web Security Study Plan': study-plan/web-security-study-plan.md
        - 'Application Security Study Plan': study-plan/application-security-study-plan.md
        - 'Python for Security Study Plan': study-plan/python-for-security-study-plan.md
        - 'Docker Security Study Plan': study-plan/docker-security-study-plan.md
        - 'Kubernetes Security Study Plan': study-plan/kubernetes-security-study-plan.md
    - Miscellaneous:
      - 'Linux Commands': miscellaneous/linux-commands.md
      - 'ViM for Everyone': miscellaneous/vim-essentials.md
      - 'Regular Expression Essentials': miscellaneous/regular-expression.md
      - 'Git Essentials with Examples': miscellaneous/git-basics.md

extra:
  consent:
    title: Cookie consent
    description: >-
      We use cookies to recognize your repeated visits and preferences, as well
      as to measure the effectiveness of our documentation and whether users
      find what they're searching for. With your consent, you're helping us to
      make our documentation better.

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/jassics
      name: follow Sanjeev Jaiswal
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/jassics
      name: follow Sanjeev Jaiswal
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/jassics
      name: connect Sanjeev on Linkedin
  generator: false