site_name: CyberCloud Learnings
site_url: https://cybercloud.guru/
site_description: Tutorials for Cloud Technologies and Cybersecurity with an easy to understand examples and projects
site_author: Sanjeev Jaiswal (Jassi)
copyright: '&copy; Copyright 2021 - Developed with Care by Cybercloud Team'
repo_url: https://github.com/jassics/CybercloudLearning
repo_name: jassics/CybercloudLearning

nav:
    - Home: index.md
    - Cloud Computing:
      - 'Cloud Computing Essentials': cloud-computing/cloud-fundamentals/cloud-basics.md
      - 'Learning AWS':
        - 'AWS Overview': cloud-computing/learning-aws/index.md
        - 'IAM': cloud-computing/learning-aws/iam.md
        - 'EC2': cloud-computing/learning-aws/ec2.md
        - 'S3': cloud-computing/learning-aws/s3.md
        - 'VPC': cloud-computing/learning-aws/vpc.md
        - 'Lambda': cloud-computing/learning-aws/lambda.md
      - 'Learning GCP':
        - 'GCP Overview': cloud-computing/learning-gcp/index.md
      - 'Learning Azure':
            - 'Azure Overview': cloud-computing/learning-azure/index.md
    - Cloud Security:
      - 'Cloud Security Essentials': cloud-security/cloud-security-basics/cloud-security.md
      - 'Learning AWS Security':
        - 'AWS Security Overview': cloud-security/learning-aws-security/aws-security-overview.md
        - 'IAM Security': cloud-security/learning-aws-security/iam-security.md
        - 'S3 Security': cloud-security/learning-aws-security/s3-security.md
      - 'Learning GCP Security':
        - 'AWS Security Overview': cloud-security/learning-gcp-security/gcp-security-overview.md
      - 'Learning Aazure Security':
        - 'AWS Security Overview': cloud-security/learning-azure-security/azure-security-overview.md
    - Containers:
        - 'Container Overview': containers/container-overview.md
        - 'Docker': containers/docker.md
        - 'Docker Security': containers/docker-security.md
        - 'Kubernetes': containers/kubernetes.md
        - 'Kubernetes Security': containers/kubernetes-security.md
    - Cybersecurity:
      - 'Cybersecurity Overview': cybersecurity/cybersecurity-overview.md
      - 'Web Security': cybersecurity/web-security.md
      - 'Network Security': cybersecurity/network-security.md
      - 'API Security': cybersecurity/api-security.md
      - 'Application Security':
          - 'Secure Coding': cybersecurity/application-security/secure-coding.md
          - 'Secure Code Review': cybersecurity/application-security/secure-code-review.md
          - 'Cryptography': cybersecurity/application-security/cryptography
          - 'Threat Modeling': cybersecurity/application-security/threat-modeling.md
          - 'SAST and SCA': cybersecurity/application-security/sast-sca.md
    - DevOps:
        - 'Understanding DevOps': devops/devops-introduction.md
        - 'Ansible': devops/ansible.md
        - 'Terraform': devops/terraform.md
        - 'CloudFormation': devops/cloudformation.md
        - 'Pulumi': devops/pulumi.md
    - GRC:
      - 'GRC Overview': grc/grc-overview.md
    - Python Track:
        - 'Python Track Introduction': python-track/introduction.md
        - 'Learning Python': python-track/learning-python.md
        - 'Python for AWS': python-track/python-for-aws.md
        - 'Python for Automation': python-track/python-for-automation.md
        - 'Python for DevOps': python-track/python-for-devops.md
        - 'Python for Cybersecurity': python-track/python-for-cybersecurity.md
    - Miscellaneous:
      - 'Linux Commands': miscellaneous/linux-commands.md
      - 'ViM for Everyone': miscellaneous/vim-essentials.md
      - 'Regular Expression Essentials': miscellaneous/regular-expression.md
      - 'Git Essentials with Examples': miscellaneous/git-basics.md

theme:
  name: material
  nav_style: dark
  analytics:
    gtag: G-ABC123
  features:
    - navigation.top
    - navigation.tabs
    - navigation.tracking
  palette:
    # Light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: light blue
      accent: blue grey
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    # Dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: light blue
      accent: light blue
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode